const SECOND_MS = 1_000;

export const DEALER_PROVISION = {
	defaultUrl: "https://www.aerolot.ai/api/admin/dealers?source=sales-espo",
	connectTimeoutMs: 5 * SECOND_MS,
	timeoutMs: 45 * SECOND_MS,
	event: "aisales_company_provisioned",
	source: "company_action",
	statuses: {
		pending: "pending",
		provisioned: "provisioned",
		failed: "failed",
		skipped: "skipped",
	},
	planTiers: ["Growth", "Professional", "Enterprise"] as const,
	usStates: [
		"AL",
		"AK",
		"AZ",
		"AR",
		"CA",
		"CO",
		"CT",
		"DE",
		"FL",
		"GA",
		"HI",
		"ID",
		"IL",
		"IN",
		"IA",
		"KS",
		"KY",
		"LA",
		"ME",
		"MD",
		"MA",
		"MI",
		"MN",
		"MS",
		"MO",
		"MT",
		"NE",
		"NV",
		"NH",
		"NJ",
		"NM",
		"NY",
		"NC",
		"ND",
		"OH",
		"OK",
		"OR",
		"PA",
		"RI",
		"SC",
		"SD",
		"TN",
		"TX",
		"UT",
		"VT",
		"VA",
		"WA",
		"WV",
		"WI",
		"WY",
		"DC",
		"PR",
		"GU",
		"VI",
		"AS",
		"MP",
	] as const,
	idempotencyKey: (companyId: string) => `aisales:company:${companyId}`,
	externalAccountId: (companyId: string) => `aisales:${companyId}`,
} as const;

export type DealerPlanTier = (typeof DEALER_PROVISION.planTiers)[number];
export type AerolotProvisionStatus =
	(typeof DEALER_PROVISION.statuses)[keyof typeof DEALER_PROVISION.statuses];
